name: unicorndial
description: Floating Action Button with Speed Dial
version: 0.0.1
author: Tiago Martins <tiagojencmartins@gmail.com>
homepage: https://github.com/tiagojencmartins

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.17.1 <3.0.0"
